IF(GIT_EXECUTABLE)
  EXECUTE_PROCESS(
    COMMAND ${GIT_EXECUTABLE} describe --tags --abbrev=0 --match "[0-9]*.[0-9A-Za-z]*"
    OUTPUT_VARIABLE VERSION_TAG
    OUTPUT_STRIP_TRAILING_WHITESPACE
    RESULT_VARIABLE TAG_OK
  )
  IF(NOT TAG_OK EQUAL 0 OR "${VERSION_TAG}" STREQUAL "")
    SET(VERSION_TAG ".C")
  ENDIF()

  EXECUTE_PROCESS(
    COMMAND ${GIT_EXECUTABLE} log -1 --date=format:%Y%m%d --format=%cd
    OUTPUT_VARIABLE COMMIT_DATE
    OUTPUT_STRIP_TRAILING_WHITESPACE
  )

  EXECUTE_PROCESS(
    COMMAND ${GIT_EXECUTABLE} diff --quiet
    RESULT_VARIABLE WORKTREE_DIRTY
  )

  SET(VERSION "${VERSION_TAG}_${COMMIT_DATE}")
  IF(NOT WORKTREE_DIRTY EQUAL 0)
    SET(VERSION "${VERSION}-cuphwi")
  ENDIF()
ELSE()
  SET(VERSION "_00000000")
ENDIF()

CONFIGURE_FILE(${SRC} ${DST} @ONLY)
